"""add_tags

Revision ID: 38ca41614ca6
Revises: 4c362f629dc0
Create Date: 2025-04-06 03:25:24.911849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '38ca41614ca6'
down_revision: Union[str, None] = '4c362f629dc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users_tags_association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'tag_id')
    )
    userroletype = postgresql.ENUM('user', 'admin', name='userroletype')
    userroletype.create(op.get_bind())
    op.add_column('users', sa.Column('role', sa.Enum('user', 'admin', name='userroletype'), server_default='user', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_table('users_tags_association')
    op.drop_table('tags')
    userroletype = postgresql.ENUM('user', 'admin', name='userroletype')
    userroletype.drop(op.get_bind())
    # ### end Alembic commands ###
