"""add_banlist_table

Revision ID: 58892425fd48
Revises: a2faf1a72d5a
Create Date: 2025-04-13 07:24:04.462881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from migration.TableInit import TableInit


# revision identifiers, used by Alembic.
revision: str = '58892425fd48'
down_revision: Union[str, None] = '7d9fdc840145'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    ban_list = op.create_table('user_ban_list',
    sa.Column('blocker_id', sa.Integer(), nullable=False),
    sa.Column('blocked_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blocker_id', 'blocked_id'),
    sa.CheckConstraint('blocker_id != blocked_id')
    )
    TableInit.insert_data_from_file(ban_list, './migration/csv_data/ban.csv')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_ban_list')
    # ### end Alembic commands ###
