"""add_meeting_table

Revision ID: 6a09c7fee5dc
Revises: 9349479bc07a
Create Date: 2025-04-14 21:11:11.340090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from migration.TableInit import TableInit

# revision identifiers, used by Alembic.
revision: str = '6a09c7fee5dc'
down_revision: Union[str, None] = '58892425fd48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    meeting_status_type = postgresql.ENUM('planned', 'canceled', 'completed', name='meetingstatustype')
    
    meeting = op.create_table('meetings',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('status', meeting_status_type, server_default='planned', nullable=False),
    sa.Column('meeting_datetime_start', sa.DateTime(), nullable=False),
    sa.Column('meeting_datetime_end', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('meeting_datetime_end > meeting_datetime_start'),
    sa.PrimaryKeyConstraint('id')
    )
    TableInit.insert_data_from_file(meeting, './migration/csv_data/meetings.csv', ['meeting_id', 'creater_id', 'joiner_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meetings')
    meeting_status_type = postgresql.ENUM('planned', 'canceled', 'completed', name='meetingstatustype')
    meeting_status_type.drop(op.get_bind())
    # ### end Alembic commands ###
