"""add_meeting_member_table

Revision ID: 9b07891ac69d
Revises: 6a09c7fee5dc
Create Date: 2025-04-14 22:28:12.658504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from migration.TableInit import TableInit

# revision identifiers, used by Alembic.
revision: str = '9b07891ac69d'
down_revision: Union[str, None] = '6a09c7fee5dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    members = op.create_table('meeting_members',
    sa.Column('meeting_id', sa.Integer(), nullable=False, index=True),
    sa.Column('user_id', sa.Integer(), nullable=False, index=True),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'meeting_id')
    )
    TableInit.insert_data_from_file(members, './migration/csv_data/meeting_members.csv')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting_members')
    # ### end Alembic commands ###
